version: '3.8'

services:
  mysqldb:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userinfo
    container_name: "mysqldb"
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10

  python:
    build: ./
    container_name: mypyapp
    depends_on:
      mysqldb:
        condition: service_healthy
    stdin_open: true
    tty: true
    links:
      - mysqldb
